### ISSUE TITLE
dpkg-buildpackage -b fails on fresh build

### ISSUE THREAD

**Issue by jniehaus1** [HogeAerospaceInstitute/gs-manager#33]
`dh_gencontrol` finds that `debian/gsmgr/DEBIAN` already exists, and fails out of the build.

Deleting this file and running the next two lines `dh_gencontrol` and `dh_builddeb` gets past the problem.

Final build command was `sudo dpkg -i`

**Comment by jrenkema** [comment]
Fixed.
