### ISSUE TITLE
2 Line TLEs cause seg faults

### ISSUE THREAD

**Issue by jniehaus1** [HogeAerospaceInstitute/gs-manager#37]
When a TLE is only two lines from the API, the task is still recorded and the info passed on to Predict, leading to some sort of seg fault. This happens for both `Get Position` on a satellite without a name, and a task with a TLE that has no 3rd line.

Suggested fix: reject all TLEs that aren't the proper format, and enforce this on the server side as well.

**Comment by jrenkema** [comment]
Fixed crash and added alert message that will be displayed on UI in case of unsupported TLE downloaded from server.
